social_discord.settings:
  type: config_object
  label: 'Social Discord settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to be requested'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
    add_roles:
      type: sequence
      label: 'Roles to add to authenticated Discord users'
      sequence:
        type: string
        label: 'Role'
    guild_id:
      type: string
      label: 'A guild to join the user to upon login'
    bot_token:
      type: string
      label: 'A bot token'
